### Get index
GET {{host}}


### Sign up
POST {{host}}/auth/sign-up
Content-Type: application/json

{
  "email": "tlna95@icloud.com",
  "password": "31121995",
  "oauthProvider": "a scdsac ",
  "oauthId": "ascasc  ",
  "firstName": "Nguyen Anh Tuan",
  "lastName": "Le",
  "role": "user"
}


### Sign in
POST {{host}}/auth/sign-in
Content-Type: application/json

{
  "email": "tlna95@icloud.com",
  "password": "31121995"
}

> {%
  client.global.set("access_token", response.body['access_token'])
%}


### Get user
GET {{host}}/user
Authorization: Bearer {{access_token}}


### Get all users
GET {{host}}/users
Authorization: Bearer {{access_token}}


### Create event
POST {{host}}/event
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "title": "Event title",
  "description": "Event description",
  "location": "Event location",
  "startAt": 1708461822000,
  "endAt": 1708461822001,
  "isValid": true
}


### Get upcoming events
GET {{host}}/events/upcoming
Authorization: Bearer {{access_token}}

> {%
  client.global.set("event_id", response.body[0]['_id'])
%}


### Get event
GET {{host}}/event/get-by-id/{{event_id}}
Authorization: Bearer {{access_token}}

> {%
  client.global.set("event_id", response.body['_id'])
%}


### Another user sign in
POST {{host}}/auth/sign-in
Content-Type: application/json

{
  "email": "admin@email.com",
  "password": "admin@123"
}
> {%
  client.global.set("access_token", response.body['access_token'])
%}


### Join event
GET {{host}}/event/join/{{event_id}}
Authorization: Bearer {{access_token}}

> {%
  client.global.set("event_id", response.body['_id'])
%}


### Leave event
GET {{host}}/event/leave/{{event_id}}
Authorization: Bearer {{access_token}}


### Admin sign in
POST {{host}}/auth/sign-in
Content-Type: application/json

{
  "email": "admin@email.com",
  "password": "admin@123"
}
> {%
  client.global.set("admin_access_token", response.body['access_token'])
%}


### Admin sign up admin
POST {{host}}/admin/sign-up
Content-Type: application/json
Authorization: Bearer {{admin_access_token}}

{
  "email": "new_admin@email.com",
  "password": "admin@123",
  "firstName": "Admin first name",
  "lastName": "Admin last name",
  "role": "admin"
}


### New admin sign in
POST {{host}}/auth/sign-in
Content-Type: application/json

{
  "email": "new_admin@email.com",
  "password": "admin@123"
}
> {%
  client.global.set("admin_access_token", response.body['access_token'])
%}



### Admin get all users
GET {{host}}/admin/users
Authorization: Bearer {{admin_access_token}}


### Admin get all events
GET {{host}}/admin/events
Authorization: Bearer {{admin_access_token}}