### Get index
GET {{host}}


### Sign up
POST {{host}}/auth/sign-up
Content-Type: application/json

{
  "email": "john",
  "password": "changeme"
}


### Sign in
POST {{host}}/auth/sign-in
Content-Type: application/json

{
  "email": "john",
  "password": "changeme"
}

> {%
  client.global.set("access_token", response.body['access_token'])
%}


### Get user
GET {{host}}/user
Authorization: Bearer {{access_token}}